#############################################################################
# Makefile for building: libartnetout.so
# Generated by qmake (2.01a) (Qt 4.7.2) on: Wed Apr 27 01:43:59 2011
# Project:  artnetout.pro
# Template: lib
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile artnetout.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -I/usr/include/libartnet -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Werror -g -I/usr/include/libartnet -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I../interfaces -I. -I.
LINK          = g++
LFLAGS        = -shared
LIBS          = $(SUBLIBS)  -L/usr/lib -lartnet -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = artnetthread.cpp \
		configureartnetoutdialog.cpp \
		artnetout.cpp moc_configureartnetoutdialog.cpp \
		moc_artnetout.cpp \
		moc_qlcoutplugin.cpp
OBJECTS       = artnetthread.o \
		configureartnetoutdialog.o \
		artnetout.o \
		moc_configureartnetoutdialog.o \
		moc_artnetout.o \
		moc_qlcoutplugin.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../variables.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		artnetout.pro
QMAKE_TARGET  = artnetout
DESTDIR       = 
TARGET        = libartnetout.so
TARGETD       = libartnetout.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET): ui_configureartnetoutdialog.h $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)



Makefile: artnetout.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../variables.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile artnetout.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
../../variables.pri:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile artnetout.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/artnetout1.0.0 || $(MKDIR) .tmp/artnetout1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/artnetout1.0.0/ && $(COPY_FILE) --parents artnetthread.h configureartnetoutdialog.h artnetout.h ../interfaces/qlcoutplugin.h .tmp/artnetout1.0.0/ && $(COPY_FILE) --parents artnetthread.cpp configureartnetoutdialog.cpp artnetout.cpp .tmp/artnetout1.0.0/ && $(COPY_FILE) --parents configureartnetoutdialog.ui .tmp/artnetout1.0.0/ && (cd `dirname .tmp/artnetout1.0.0` && $(TAR) artnetout1.0.0.tar artnetout1.0.0 && $(COMPRESS) artnetout1.0.0.tar) && $(MOVE) `dirname .tmp/artnetout1.0.0`/artnetout1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/artnetout1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_configureartnetoutdialog.cpp moc_artnetout.cpp moc_qlcoutplugin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_configureartnetoutdialog.cpp moc_artnetout.cpp moc_qlcoutplugin.cpp
moc_configureartnetoutdialog.cpp: configureartnetoutdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) configureartnetoutdialog.h -o moc_configureartnetoutdialog.cpp

moc_artnetout.cpp: artnetthread.h \
		artnetout.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) artnetout.h -o moc_artnetout.cpp

moc_qlcoutplugin.cpp: ../interfaces/qlcoutplugin.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../interfaces/qlcoutplugin.h -o moc_qlcoutplugin.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_configureartnetoutdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_configureartnetoutdialog.h
ui_configureartnetoutdialog.h: configureartnetoutdialog.ui
	/usr/bin/uic-qt4 configureartnetoutdialog.ui -o ui_configureartnetoutdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

artnetthread.o: artnetthread.cpp artnetthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o artnetthread.o artnetthread.cpp

configureartnetoutdialog.o: configureartnetoutdialog.cpp configureartnetoutdialog.h \
		ui_configureartnetoutdialog.h \
		artnetout.h \
		artnetthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configureartnetoutdialog.o configureartnetoutdialog.cpp

artnetout.o: artnetout.cpp artnetout.h \
		artnetthread.h \
		configureartnetoutdialog.h \
		../../engine/src/qlcfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o artnetout.o artnetout.cpp

moc_configureartnetoutdialog.o: moc_configureartnetoutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configureartnetoutdialog.o moc_configureartnetoutdialog.cpp

moc_artnetout.o: moc_artnetout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_artnetout.o moc_artnetout.cpp

moc_qlcoutplugin.o: moc_qlcoutplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qlcoutplugin.o moc_qlcoutplugin.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/ 
	-$(INSTALL_PROGRAM) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

