#############################################################################
# Makefile for building: libartnetout.so
# Generated by qmake (2.01a) (Qt 4.7.1) on: Mon Apr 25 18:41:24 2011
# Project:  artnetout.pro
# Template: lib
# Command: /opt/meego/meego-sdk-qt/bin/qmake -spec /opt/meego/meego-sdk-qt/share/qt4/mkspecs/linux-g++-64 QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile artnetout.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -Werror -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/opt/meego/meego-sdk-qt/share/qt4/mkspecs/linux-g++-64 -I. -I/opt/meego/meego-sdk-qt/include/qt4/QtCore -I/opt/meego/meego-sdk-qt/include/qt4/QtGui -I/opt/meego/meego-sdk-qt/include/qt4 -I../interfaces -I. -I.
LINK          = g++
LFLAGS        = -m64 -shared
LIBS          = $(SUBLIBS)  -L/opt/meego/meego-sdk-qt/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/meego/meego-sdk-qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = artnetout.cpp \
		artnetthread.cpp \
		configureartnetout.cpp \
		configureartnetoutdialog.cpp moc_artnetout.cpp \
		moc_configureartnetout.cpp \
		moc_qlcoutplugin.cpp \
		moc_configureartnetoutdialog.cpp
OBJECTS       = artnetout.o \
		artnetthread.o \
		configureartnetout.o \
		configureartnetoutdialog.o \
		moc_artnetout.o \
		moc_configureartnetout.o \
		moc_qlcoutplugin.o \
		moc_configureartnetoutdialog.o
DIST          = /opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/g++.conf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/unix.conf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/linux.conf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/qconfig.pri \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt_config.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/default_pre.prf \
		../../variables.pri \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/debug.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/default_post.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/warn_on.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/moc.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/resources.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/uic.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/yacc.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/lex.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/include_source_dir.prf \
		artnetout.pro
QMAKE_TARGET  = artnetout
DESTDIR       = 
TARGET        = libartnetout.so
TARGETD       = libartnetout.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET): ui_configureartnetout.h ui_configureartnetoutdialog.h $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)



Makefile: artnetout.pro  /opt/meego/meego-sdk-qt/share/qt4/mkspecs/linux-g++-64/qmake.conf /opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/g++.conf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/unix.conf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/linux.conf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/qconfig.pri \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt_config.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/default_pre.prf \
		../../variables.pri \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/debug.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/default_post.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/warn_on.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/moc.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/resources.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/uic.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/yacc.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/lex.prf \
		/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/meego/meego-sdk-qt/lib/libQtGui.prl \
		/opt/meego/meego-sdk-qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/meego/meego-sdk-qt/share/qt4/mkspecs/linux-g++-64 QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile artnetout.pro
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/g++.conf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/unix.conf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/common/linux.conf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/qconfig.pri:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt_functions.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt_config.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/default_pre.prf:
../../variables.pri:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/debug.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/default_post.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/warn_on.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/qt.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/unix/thread.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/moc.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/resources.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/uic.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/yacc.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/lex.prf:
/opt/meego/meego-sdk-qt/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/meego/meego-sdk-qt/lib/libQtGui.prl:
/opt/meego/meego-sdk-qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/meego/meego-sdk-qt/share/qt4/mkspecs/linux-g++-64 QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile artnetout.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/artnetout1.0.0 || $(MKDIR) .tmp/artnetout1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/artnetout1.0.0/ && $(COPY_FILE) --parents artnetout.h artnetthread.h configureartnetout.h ../interfaces/qlcoutplugin.h configureartnetoutdialog.h .tmp/artnetout1.0.0/ && $(COPY_FILE) --parents artnetout.cpp artnetthread.cpp configureartnetout.cpp configureartnetoutdialog.cpp .tmp/artnetout1.0.0/ && $(COPY_FILE) --parents configureartnetout.ui configureartnetoutdialog.ui .tmp/artnetout1.0.0/ && (cd `dirname .tmp/artnetout1.0.0` && $(TAR) artnetout1.0.0.tar artnetout1.0.0 && $(COMPRESS) artnetout1.0.0.tar) && $(MOVE) `dirname .tmp/artnetout1.0.0`/artnetout1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/artnetout1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_artnetout.cpp moc_configureartnetout.cpp moc_qlcoutplugin.cpp moc_configureartnetoutdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_artnetout.cpp moc_configureartnetout.cpp moc_qlcoutplugin.cpp moc_configureartnetoutdialog.cpp
moc_artnetout.cpp: artnetthread.h \
		artnetout.h
	/opt/meego/meego-sdk-qt/bin/moc $(DEFINES) $(INCPATH) artnetout.h -o moc_artnetout.cpp

moc_configureartnetout.cpp: ui_configureartnetout.h \
		configureartnetout.h
	/opt/meego/meego-sdk-qt/bin/moc $(DEFINES) $(INCPATH) configureartnetout.h -o moc_configureartnetout.cpp

moc_qlcoutplugin.cpp: ../interfaces/qlcoutplugin.h
	/opt/meego/meego-sdk-qt/bin/moc $(DEFINES) $(INCPATH) ../interfaces/qlcoutplugin.h -o moc_qlcoutplugin.cpp

moc_configureartnetoutdialog.cpp: configureartnetoutdialog.h
	/opt/meego/meego-sdk-qt/bin/moc $(DEFINES) $(INCPATH) configureartnetoutdialog.h -o moc_configureartnetoutdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_configureartnetout.h ui_configureartnetoutdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_configureartnetout.h ui_configureartnetoutdialog.h
ui_configureartnetout.h: configureartnetout.ui
	/opt/meego/meego-sdk-qt/bin/uic configureartnetout.ui -o ui_configureartnetout.h

ui_configureartnetoutdialog.h: configureartnetoutdialog.ui
	/opt/meego/meego-sdk-qt/bin/uic configureartnetoutdialog.ui -o ui_configureartnetoutdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

artnetout.o: artnetout.cpp artnetout.h \
		artnetthread.h \
		configureartnetoutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o artnetout.o artnetout.cpp

artnetthread.o: artnetthread.cpp artnetthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o artnetthread.o artnetthread.cpp

configureartnetout.o: configureartnetout.cpp configureartnetout.h \
		ui_configureartnetout.h \
		artnetout.h \
		artnetthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configureartnetout.o configureartnetout.cpp

configureartnetoutdialog.o: configureartnetoutdialog.cpp configureartnetoutdialog.h \
		ui_configureartnetoutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configureartnetoutdialog.o configureartnetoutdialog.cpp

moc_artnetout.o: moc_artnetout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_artnetout.o moc_artnetout.cpp

moc_configureartnetout.o: moc_configureartnetout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configureartnetout.o moc_configureartnetout.cpp

moc_qlcoutplugin.o: moc_qlcoutplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qlcoutplugin.o moc_qlcoutplugin.cpp

moc_configureartnetoutdialog.o: moc_configureartnetoutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configureartnetoutdialog.o moc_configureartnetoutdialog.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/ 
	-$(INSTALL_PROGRAM) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/plugins/qlc/input/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

